// World parity: the C++ generator against the JavaScript one.
//
// A port that is "close" is worse than no port, because every downstream claim
// about the native renderer is then about a different city. This test runs the
// JavaScript generator, dumps a fixture of the values both implementations
// produce, and asserts the C++ matches to a tolerance tight enough that a
// building cannot move by even a centimetre.
//
// The fixture is generated by `tools/gen_world_fixture.mjs` and committed. It is
// committed rather than generated at test time because the test must run
// without Node, and because a committed fixture is a record of what the port
// was compared against -- if the JavaScript world changes, this test fails and
// someone has to decide whether that was intended.
//
// The tolerances are chosen per-quantity. Terrain is summed from fbm over
// several octaves, so a last-ulp difference in `sin` compounds; buildings come
// from integer draws and must agree exactly; counts are integers and must agree
// exactly.

#include "emergent/world_gen.hpp"

#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

namespace {

int g_failures = 0;
int g_checks = 0;

void check(bool ok, const std::string &what) {
    g_checks++;
    if (!ok) {
        g_failures++;
        std::printf("  FAIL %s\n", what.c_str());
    }
}

void checkNear(double a, double b, double tol, const std::string &what) {
    g_checks++;
    if (!(std::fabs(a - b) <= tol)) {
        g_failures++;
        std::printf("  FAIL %s: %.9f vs %.9f (tolerance %g)\n", what.c_str(), a, b, tol);
    }
}

// A whitespace-separated list of doubles, one per line in the fixture.
std::vector<double> readColumn(const std::string &path, const std::string &key) {
    std::vector<double> out;
    std::ifstream in(path);
    std::string line;
    bool inSection = false;
    while (std::getline(in, line)) {
        if (line.rfind("[", 0) == 0) {
            inSection = line.find("[" + key + "]") != std::string::npos;
            continue;
        }
        if (!inSection) continue;
        std::istringstream ss(line);
        double v;
        while (ss >> v) out.push_back(v);
    }
    return out;
}

}  // namespace

// Find the fixture whether the test is run from the source root (the way a
// developer does it) or from the build directory (the way ctest does it). A
// relative path that only works from one of the two is a test that fails in CI
// and passes locally, which is the worst of both.
static std::string findFixture(int argc, char **argv) {
    if (argc > 1) return argv[1];
    const char *candidates[] = {
        "native/tests/world_fixture.txt",
        "../native/tests/world_fixture.txt",
        "../../native/tests/world_fixture.txt",
    };
    for (const char *c : candidates) {
        std::ifstream probe(c);
        if (probe) return c;
    }
    return "native/tests/world_fixture.txt";
}

int main(int argc, char **argv) {
    const std::string fixturePath = findFixture(argc, argv);
    std::ifstream probe(fixturePath);
    if (!probe) {
        std::printf("world parity: fixture %s is missing — run `npm run test:fixture`\n", fixturePath.c_str());
        return 1;
    }
    probe.close();

    // -- terrain ------------------------------------------------------------
    // Sampled on a fixed lattice, including the origin and the far corner. The
    // tolerance is 1e-6 m on a terrain whose range is tens of metres: that is
    // float noise, not a disagreement about where a hill is.
    const auto heights = readColumn(fixturePath, "terrain");
    check(!heights.empty(), "the fixture has terrain samples");
    check(heights.size() % 3 == 0, "the terrain fixture is a whole number of rows");
    if (!heights.empty()) {
        const int n = static_cast<int>(heights.size() / 3);
        for (int i = 0; i < n; i++) {
            const double x = heights[static_cast<size_t>(i) * 3];
            const double z = heights[static_cast<size_t>(i) * 3 + 1];
            const double expected = heights[static_cast<size_t>(i) * 3 + 2];
            const double got = emergent::terrainHeight(x, z, 173927);
            // 1e-6 absolute. The world is 9600 m across; a 1 micrometre
            // disagreement is far below the smallest thing the game can show.
            char buf[160];
            std::snprintf(buf, sizeof(buf), "terrainHeight(%.1f, %.1f)", x, z);
            checkNear(got, expected, 1e-6, buf);
        }
    }

    // -- the seeded generators ---------------------------------------------
    // These are the load-bearing ones. If `ihash` or the xorshift diverges,
    // everything downstream diverges with it, and the terrain check above
    // would be the first place it showed.
    const auto hashes = readColumn(fixturePath, "ihash");
    check(!hashes.empty(), "the fixture has ihash samples");
    // Four values per row: x, y, seed, result. Reading the stride as three made
    // the test compare a hash against the *x* that produced it, which fails
    // loudly -- but the loop then also ran off the end of the vector, and that
    // segfaulted before the failure was reported. Stride and bounds check are
    // now both explicit.
    for (size_t i = 0; i + 3 < hashes.size(); i += 4) {
        const double got = emergent::ihash(static_cast<int32_t>(hashes[i]), static_cast<int32_t>(hashes[i + 1]),
                                           static_cast<int32_t>(hashes[i + 2]));
        char buf[160];
        std::snprintf(buf, sizeof(buf), "ihash(%d, %d, %d)", static_cast<int>(hashes[i]),
                      static_cast<int>(hashes[i + 1]), static_cast<int>(hashes[i + 2]));
        // An integer hash divides an exact power-of-two range by an exact
        // power of two, so this is bit-exact and the tolerance is a guard
        // against a future change to the fixture format rather than a fudge.
        checkNear(got, hashes[i + 3], 1e-15, buf);
    }
    check(hashes.size() % 4 == 0, "the ihash fixture is a whole number of rows");

    const auto rngs = readColumn(fixturePath, "rng");
    check(rngs.size() >= 2, "the fixture has rng samples");
    if (rngs.size() >= 2) {
        // Compared as integers, not as the printed double. The generator is
        // exact -- it is a 32-bit integer divided by a power of two -- but the
        // fixture stores fifteen decimal places, and demanding that a
        // `double / 4294967296.0` round-trips through text to the identical bit
        // pattern tests the printer, not the port. So the raw integer draw is
        // reconstructed from the fraction and compared to the exact integer the
        // C++ side produces.
        emergent::Rng r(static_cast<uint32_t>(rngs[0]));
        for (size_t i = 1; i < rngs.size(); i++) {
            const uint32_t expected = static_cast<uint32_t>(std::llround(rngs[i] * 4294967296.0));
            char buf[128];
            std::snprintf(buf, sizeof(buf), "rng draw %zu (integer)", i);
            check(r.next() == expected, buf);
        }
    }

    // -- the world ----------------------------------------------------------
    const emergent::World w = emergent::generateWorld(173927);

    const auto counts = readColumn(fixturePath, "counts");
    if (counts.size() >= 6) {
        char buf[160];
        // The counts are printed to six decimal places and read back as
        // doubles, so they are compared as rounded integers rather than with
        // `==` on a size_t that happens to convert exactly.
        auto expect = [&](size_t got, double want, const char *name) {
            std::snprintf(buf, sizeof(buf), "%s count (%zu vs %.0f)", name, got, want);
            check(got == static_cast<size_t>(std::llround(want)), buf);
        };
        expect(w.regions.size(), counts[0], "region");
        expect(w.districts.size(), counts[1], "district");
        expect(w.roads.size(), counts[2], "road");
        expect(w.buildings.size(), counts[3], "building");
        expect(w.trees.size(), counts[4], "tree");
        expect(w.businesses.size(), counts[5], "business");
        if (counts.size() >= 9) {
            expect(w.npcs.size(), counts[6], "npc");
            expect(w.cars.size(), counts[7], "car");
            expect(w.water.size(), counts[8], "water");
        }
    }

    const auto buildings = readColumn(fixturePath, "buildings");
    check(!buildings.empty(), "the fixture has building samples");
    check(buildings.size() % 6 == 0, "the building fixture is a whole number of rows");
    if (!buildings.empty()) {
        const size_t n = buildings.size() / 6;
        check(n <= w.buildings.size(), "the fixture does not claim more buildings than exist");
        for (size_t i = 0; i < n && i < w.buildings.size(); i++) {
            const emergent::Building &b = w.buildings[i];
            char buf[200];
            // The fixture stores six decimal places, so a position is only
            // pinned to a micrometre. That is five orders of magnitude tighter
            // than the smallest thing the renderer places (a kerb at 0.14 m) and
            // still catches a diverged random stream, which would move a
            // building by metres.
            std::snprintf(buf, sizeof(buf), "building %zu x", i);
            checkNear(b.x, buildings[i * 6], 1e-6, buf);
            std::snprintf(buf, sizeof(buf), "building %zu z", i);
            checkNear(b.z, buildings[i * 6 + 1], 1e-6, buf);
            std::snprintf(buf, sizeof(buf), "building %zu width", i);
            checkNear(b.w, buildings[i * 6 + 2], 1e-6, buf);
            std::snprintf(buf, sizeof(buf), "building %zu depth", i);
            checkNear(b.d, buildings[i * 6 + 3], 1e-6, buf);
            std::snprintf(buf, sizeof(buf), "building %zu height", i);
            checkNear(b.h, buildings[i * 6 + 4], 1e-6, buf);
            // The archetype is an integer draw and must match exactly.
            std::snprintf(buf, sizeof(buf), "building %zu kind", i);
            check(b.kind == static_cast<int32_t>(std::llround(buildings[i * 6 + 5])), buf);
        }
    }

    const auto roads = readColumn(fixturePath, "roads");
    check(roads.empty() || roads.size() % 5 == 0, "the road fixture is a whole number of rows");
    if (!roads.empty()) {
        const size_t n = roads.size() / 5;
        check(n <= w.roads.size(), "the fixture does not claim more roads than exist");
        for (size_t i = 0; i < n && i < w.roads.size(); i++) {
            const emergent::Road &r = w.roads[i];
            char buf[160];
            std::snprintf(buf, sizeof(buf), "road %zu x", i);
            checkNear(r.x, roads[i * 5], 1e-6, buf);
            std::snprintf(buf, sizeof(buf), "road %zu z", i);
            checkNear(r.z, roads[i * 5 + 1], 1e-6, buf);
            std::snprintf(buf, sizeof(buf), "road %zu width", i);
            checkNear(r.w, roads[i * 5 + 2], 1e-6, buf);
            std::snprintf(buf, sizeof(buf), "road %zu depth", i);
            checkNear(r.d, roads[i * 5 + 3], 1e-6, buf);
            std::snprintf(buf, sizeof(buf), "road %zu class", i);
            check(r.kind == static_cast<int32_t>(std::llround(roads[i * 5 + 4])), buf);
        }
    }

    const auto river = readColumn(fixturePath, "river");
    if (!river.empty()) {
        // The river position comes from a `sin`, so it is compared with the one
        // tolerance in the suite that is not exact.
        checkNear(w.riverX, river[0], 1e-9, "river x");
    }

    // -- determinism --------------------------------------------------------
    // A generator that returns a different world for the same seed makes every
    // other check in this file meaningless, and does so intermittently.
    const emergent::World again = emergent::generateWorld(173927);
    check(again.buildings.size() == w.buildings.size(), "the generator is deterministic in size");
    for (size_t i = 0; i < w.buildings.size(); i++) {
        if (again.buildings[i].x != w.buildings[i].x) {
            check(false, "the generator is deterministic in position");
            break;
        }
    }
    const emergent::World other = emergent::generateWorld(173928);
    check(other.buildings.size() != w.buildings.size() ||
              other.buildings[0].x != w.buildings[0].x,
          "a different seed produces a different world");

    if (g_failures) {
        std::printf("\n%d of %d world parity checks FAILED\n", g_failures, g_checks);
        return 1;
    }
    std::printf("world parity: %d checks passed (%zu buildings, %zu roads, %zu districts)\n",
                g_checks, w.buildings.size(), w.roads.size(), w.districts.size());
    return 0;
}
