#!/usr/bin/env node
/**
 * Generate the world-parity fixture.
 *
 * The C++ world generator is a port of `world.mjs` and has to agree with it
 * exactly, or the native renderer is drawing a different city from the one the
 * reference implementation describes and every cross-check between them is
 * worthless. `native/tests/world_parity_test.cpp` asserts that agreement
 * against a fixture this script writes.
 *
 * The fixture is committed rather than generated during the test for two
 * reasons: the native test suite has to run on a machine with no Node, and a
 * committed fixture is a record of what the port was compared against. If
 * `world.mjs` changes, the parity test fails and someone has to decide whether
 * that change was meant to move the native world too.
 *
 * Run: `npm run test:fixture`
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateWorld, terrainHeight, WORLD_SIZE } from '../world.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'native', 'tests', 'world_fixture.txt');

const SEED = 173927;
const lines = [];

/** How many of each record the fixture pins. */
const SAMPLE = 400;

lines.push('# EMERGENT world parity fixture.');
lines.push('#');
lines.push('# Generated by `npm run test:fixture` from world.mjs. Do not edit by hand:');
lines.push('# native/tests/world_parity_test.cpp asserts the C++ port in world_gen.cpp');
lines.push('# reproduces every value below, and hand-editing it makes the test lie.');
lines.push(`# seed: ${SEED}`);
lines.push('');

lines.push('[terrain]');
lines.push('# x z height -- sampled on a fixed lattice including the origin and corners.');
{
  const samples = [];
  for (let i = 0; i < 16; i++) {
    for (let j = 0; j < 16; j++) {
      const x = (i / 15) * WORLD_SIZE * 0.98;
      const z = (j / 15) * WORLD_SIZE * 0.98;
      samples.push(`${x.toFixed(6)} ${z.toFixed(6)} ${terrainHeight(x, z, SEED).toFixed(9)}`);
    }
  }
  // A few exact landmarks as well, including the origin, because a lattice can
  // miss a bug that only shows at zero.
  for (const [x, z] of [[0, 0], [4800, 4800], [9500, 9500], [-120, 240]]) {
    samples.push(`${x.toFixed(6)} ${z.toFixed(6)} ${terrainHeight(x, z, SEED).toFixed(9)}`);
  }
  lines.push(...samples);
}
lines.push('');

lines.push('[ihash]');
lines.push('# x y seed value -- the integer lattice hash, exactly. The test is bit-exact.');
lines.push('# ihash is not exported, so it is reproduced here from world.mjs\'s definition.');
{
  // Reproduced verbatim from world.mjs. If that changes, this must change, and
  // the parity test will say so rather than passing on a stale copy.
  const ihash = (x, y, seed) => {
    let h = Math.imul(x | 0, 0x27d4eb2d) ^ Math.imul(y | 0, 0x165667b1) ^ Math.imul(seed | 0, 0x9e3779b1);
    h = Math.imul(h ^ (h >>> 15), 0x85ebca6b);
    h ^= h >>> 13;
    h = Math.imul(h, 0xc2b2ae35);
    h ^= h >>> 16;
    return (h >>> 0) / 4294967296;
  };
  const rows = [];
  for (const [x, y, s] of [[0, 0, 1], [1, 0, 1], [0, 1, 1], [1, 1, 1], [-1, -1, 1],
    [12345, 67890, 173927], [-4800, 2400, 173927], [99999, -99999, 42], [7, 13, 1]]) {
    rows.push(`${x} ${y} ${s} ${ihash(x, y, s).toFixed(15)}`);
  }
  lines.push(...rows);
}
lines.push('');

lines.push('[rng]');
lines.push('# seed d0 d1 d2 d3 d4 -- the first draws of the xorshift generator.');
{
  let s = SEED >>> 0 || 1;
  const next = () => {
    s ^= s << 13; s >>>= 0;
    s ^= s >>> 17;
    s ^= s << 5; s >>>= 0;
    return s;
  };
  const draws = [];
  for (let i = 0; i < 8; i++) draws.push((next() / 4294967296).toFixed(15));
  lines.push(`${SEED} ${draws.join(' ')}`);
}
lines.push('');

const world = generateWorld(SEED);

lines.push('[counts]');
lines.push('# regions districts roads buildings trees businesses npcs cars water');
lines.push([world.regions.length, world.districts.length, world.roads.length, world.buildings.length,
  world.trees.length, world.businesses.length, world.npcs.length, world.cars.length, world.water.length].join(' '));
lines.push('');

lines.push('[river]');
lines.push(world.riverX.toFixed(9));
lines.push('');

lines.push('[roads]');
lines.push('# x z w d class -- the arterial grid, pinned exactly. Road layout decides where');
lines.push('# every building goes, so a divergence here moves the whole city.');
{
  const rows = [];
  for (const r of world.roads.slice(0, SAMPLE)) {
    rows.push(`${r.x.toFixed(6)} ${r.z.toFixed(6)} ${r.w.toFixed(6)} ${r.d.toFixed(6)} ${r.main}`);
  }
  lines.push(...rows);
}
lines.push('');

lines.push('[buildings]');
lines.push('# x z w d h kind -- the first SAMPLE buildings. Integer draws, so exact.');
{
  const KIND = { shop: 0, tower: 1, warehouse: 2, house: 3 };
  const rows = [];
  for (const b of world.buildings.slice(0, SAMPLE)) {
    rows.push(`${b.x.toFixed(6)} ${b.z.toFixed(6)} ${b.w.toFixed(6)} ${b.d.toFixed(6)} ${b.h.toFixed(6)} ${KIND[b.kind] ?? 3}`);
  }
  lines.push(...rows);
}
lines.push('');

lines.push('[districts]');
lines.push('# x z r type -- district cores and their radius.');
{
  const TYPE = { industrial: 0, commercial: 1, residential: 2, mixed: 3 };
  const rows = [];
  for (const d of world.districts) {
    rows.push(`${d.x.toFixed(6)} ${d.z.toFixed(6)} ${d.r.toFixed(6)} ${TYPE[d.type] ?? 3}`);
  }
  lines.push(...rows);
}
lines.push('');

fs.writeFileSync(OUT, `${lines.join('\n')}\n`);

const bytes = fs.statSync(OUT).size;
console.log(`wrote ${path.relative(ROOT, OUT)} (${(bytes / 1024).toFixed(1)} KB)`);
console.log(`  ${world.regions.length} regions, ${world.districts.length} districts, ${world.roads.length} roads`);
console.log(`  ${world.buildings.length} buildings, ${world.trees.length} trees, ${world.businesses.length} businesses`);
console.log(`  ${world.npcs.length} npcs, ${world.cars.length} cars, ${world.water.length} water segments`);
